[package]
name = "bazaar_mission"
edition = "2024.beta"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
EVE = { local = "../EveCoinTypeStub" }
dapp_hub = { local = "../DappHub" }
shared_widgets = { local = "../SharedWidgets" }
WorldStub = { local = "../WorldStub" }
bazaar_core = { local = "../BazaarCore" }

[addresses]
bazaar_mission = "0xb2f01c1df61c8ffbcd48273cb499239a513c60c560e12a64743164c350224a89"
EVE = "0xac361aa5ceb726bd974f885c9dea9e55dc9bc98fa1f5731c5965a810707bf0b8"
world = "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1"
